# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-20 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import gifspool.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('tags', models.CharField(max_length=300)),
                ('upload_date', models.DateTimeField()),
                ('likes', models.TextField()),
                ('post_to', models.BooleanField(default=False)),
                ('gif_file', models.FileField(upload_to=gifspool.models.user_directory_path)),
                ('gif_path', models.FilePathField(path=gifspool.models.user_directory_path)),
            ],
        ),
    ]
