# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-23 09:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gifspool.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('num_gifs', models.IntegerField()),
                ('num_likes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Gif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default='', max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('tags', models.CharField(max_length=300)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('likes', models.TextField(default='')),
                ('post_to', models.BooleanField(default=False)),
                ('gif_file', models.FileField(upload_to=gifspool.models.user_directory_path)),
                ('gif_path', models.TextField(default='<function user_directory_path at 0x7f6f39cc1d08>')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gifspool.Category')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
