# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-20 14:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gifspool', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gif',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='gif',
            name='gif_path',
        ),
        migrations.RemoveField(
            model_name='gif',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='gif',
            name='post_to',
        ),
        migrations.RemoveField(
            model_name='gif',
            name='upload_date',
        ),
    ]
