# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-23 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifspool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gif',
            name='gif_path',
            field=models.TextField(default='<function user_directory_path at 0x7f1f46f29d08>'),
        ),
    ]
