# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-23 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifspool', '0002_auto_20170323_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gif',
            name='gif_path',
            field=models.FilePathField(path='/home/denys/projects/gifsta/media'),
        ),
    ]
