# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-20 18:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import gifspool.models


class Migration(migrations.Migration):

    dependencies = [
        ('gifspool', '0004_auto_20170320_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gif',
            name='user',
        ),
        migrations.AddField(
            model_name='gif',
            name='creator',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='gif',
            name='gif_path',
            field=models.FilePathField(default='', path=gifspool.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='gif',
            name='likes',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='gif',
            name='post_to',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gif',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
