# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-23 10:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gifspool', '0004_remove_gif_gif_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gif',
            name='user',
        ),
        migrations.AlterField(
            model_name='gif',
            name='creator',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
