# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-27 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifspool', '0004_auto_20170514_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='gif',
            name='mp4_file_url',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
