# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-23 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifspool', '0005_auto_20170323_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='gif',
            name='laugh',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='gif',
            name='loved',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='gif',
            name='shocked',
            field=models.TextField(default=''),
        ),
    ]
