# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-26 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifspool', '0005_auto_20170323_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='gif',
            name='likes_by',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='gif',
            name='likes',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
