# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-21 19:57
from __future__ import unicode_literals

from django.db import migrations, models
import gifspool.models


class Migration(migrations.Migration):

    dependencies = [
        ('gifspool', '0006_auto_20170320_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gif',
            name='gif_path',
            field=models.FilePathField(default='', path=gifspool.models.user_directory_path),
        ),
    ]
