# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-27 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifspool', '0006_auto_20170326_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='gif',
            name='laugh',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='gif',
            name='loved',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='gif',
            name='shocked',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
