# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-27 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifspool', '0007_auto_20170327_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gif',
            name='laugh',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gif',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gif',
            name='loved',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gif',
            name='shocked',
            field=models.IntegerField(default=0),
        ),
    ]
